"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { extendedLeadStatuses, statusLabel, type InquiryLead } from "@/lib/domain";

type Analytics = { total: number; overdue: number; averageConfidence: number; byStatus: Record<string, number>; byCategory: Record<string, number> };
export default function OwnerInbox() {
  const [leads, setLeads] = useState<InquiryLead[] | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [error, setError] = useState(""); const [q, setQ] = useState(""); const [status, setStatus] = useState("all");
  async function load() { const query = new URLSearchParams(); if (q) query.set("q", q); if (status !== "all") query.set("status", status); const [leadResponse, analyticsResponse] = await Promise.all([fetch(`/api/leads?${query}`), fetch("/api/analytics")]); if (leadResponse.status === 401) { window.location.href = "/owner/login"; return; } if (!leadResponse.ok || !analyticsResponse.ok) throw new Error("Could not load the workspace."); setLeads((await leadResponse.json()).leads); setAnalytics(await analyticsResponse.json()); }
  // The debounce intentionally tracks only the two query controls.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load the workspace.")); }, 180); return () => window.clearTimeout(timer); }, [q, status]);
  return <main className="owner-shell"><nav className="nav"><Link href="/" className="brand">inquiry<span>•</span>desk</Link><Link href="/owner/login" className="nav-link">Sign out ↗</Link></nav><div className="owner-top"><div><div className="eyebrow">Operator workspace / website intake</div><h1>Review queue</h1><p className="lede">Triage the queue, make the draft yours, and keep the next action visible.</p></div><div className="owner-meta">{analytics?.overdue || 0} overdue<br />{Math.round((analytics?.averageConfidence || 0) * 100)}% avg confidence</div></div>
    <div className="metric-row"><div className="metric"><small>All inquiries</small><strong>{analytics?.total ?? "…"}</strong></div><div className="metric"><small>Needs review</small><strong>{analytics?.byStatus?.needs_info || 0}</strong></div><div className="metric"><small>Sent</small><strong>{analytics?.byStatus?.sent || 0}</strong></div><a className="metric export" href="/api/leads/export"><small>Data</small><strong>Export CSV ↗</strong></a></div>
    <div className="panel"><div className="filter-row"><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search name, email, request…" aria-label="Search inquiries" /><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option value="all">All statuses</option>{extendedLeadStatuses.map((item) => <option value={item} key={item}>{statusLabel(item)}</option>)}</select></div><div className="panel-head"><h2>Incoming inquiries</h2><span className="count">{leads?.length ?? "…"}</span></div>{error ? <div className="empty error">{error}</div> : leads?.length === 0 ? <div className="empty"><strong>Your filtered queue is clear.</strong>Try another filter or share the public intake link.</div> : <div className="lead-list">{leads?.map((lead) => <Link className="lead-row" href={`/owner/leads/${lead.id}`} key={lead.id}><div className="lead-row-top"><span className="lead-name">{lead.name}</span><span className={`pill ${lead.status}`}>{statusLabel(lead.status)}</span></div><div className="lead-preview">{lead.extracted.requestedService || "General inquiry"} · {lead.request}</div><div className="lead-time">{new Date(lead.createdAt).toLocaleString()} · {lead.assignedTo || "unassigned"}</div></Link>)}</div>}</div>
  </main>;
}
