import { NextResponse } from "next/server";
import { z } from "zod";
import { errorResponse } from "@/lib/http";
import { requireOwner } from "@/lib/security";
import { getStore, statusEvent } from "@/lib/store";
import { assertTransition } from "@/lib/workflow";
import { createDeliveryProvider, deliverySubject } from "@/lib/delivery";
const bodySchema = z.object({ action: z.enum(["approve", "reject", "send", "retry", "close", "reopen"]), draft: z.string().trim().min(1).max(4000).optional().default(""), idempotencyKey: z.string().max(160).optional() });
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const session = await requireOwner(); const body = bodySchema.parse(await request.json()); const store = getStore(); const lead = await store.get(session.workspaceId, (await params).id); if (!lead) return NextResponse.json({ error: "Inquiry not found" }, { status: 404 });
    if (["approve", "reject"].includes(body.action)) {
      const next: "approved" | "rejected" = body.action === "approve" ? "approved" : "rejected"; assertTransition(lead.status, next); const version = lead.drafts.length + 1; const updated = { ...lead, draft: body.draft || lead.draft, status: next, updatedAt: new Date().toISOString(), drafts: [...lead.drafts, { id: crypto.randomUUID(), version, body: body.draft || lead.draft, status: body.action === "approve" ? "approved" : "rejected", createdAt: new Date().toISOString(), createdBy: session.userId }], events: [...lead.events, statusEvent(body.action === "approve" ? "approved" : "rejected", session.userId, body.action === "approve" ? "Draft approved; sending remains explicit" : "Draft rejected for revision") ] }; await store.save(updated); return NextResponse.json({ lead: updated });
    }
    if (body.action === "close" || body.action === "reopen") {
      const next: "closed" | "drafting" = body.action === "close" ? "closed" : "drafting"; assertTransition(lead.status, next); const updated = { ...lead, status: next, updatedAt: new Date().toISOString(), events: [...lead.events, statusEvent(body.action, session.userId, body.action === "close" ? "Outcome recorded" : "Reopened for revision") ] }; await store.save(updated); return NextResponse.json({ lead: updated });
    }
    const idempotencyKey = body.idempotencyKey || `${lead.id}:draft:${lead.drafts.at(-1)?.version || 1}`; const existing = lead.deliveries.find((delivery) => delivery.idempotencyKey === idempotencyKey); if (existing?.status === "sent") return NextResponse.json({ lead, duplicate: true }); assertTransition(lead.status, "sending"); const queuedAt = new Date().toISOString(); const provider = createDeliveryProvider(); const attempt = existing ? { ...existing, status: "sending" as const, attempts: existing.attempts + 1, updatedAt: queuedAt, lastError: undefined } : { id: crypto.randomUUID(), idempotencyKey, channel: "email" as const, recipient: lead.email, status: "sending" as const, attempts: 1, createdAt: queuedAt, updatedAt: queuedAt }; const sending = { ...lead, status: "sending" as const, updatedAt: queuedAt, deliveries: [...lead.deliveries.filter((item) => item.id !== existing?.id), attempt], events: [...lead.events, statusEvent("delivery_started", session.userId, `Provider: ${provider.name}`)] }; await store.save(sending);
    let result: { accepted: boolean; providerId?: string; error?: string }; try { result = await provider.send({ to: lead.email, subject: deliverySubject(lead), body: lead.draft, idempotencyKey }); } catch (error) { result = { accepted: false, error: error instanceof Error ? error.message : "Delivery provider failed" }; } const completedAt = new Date().toISOString(); const delivery = { ...attempt, status: result.accepted ? "sent" as const : "failed" as const, updatedAt: completedAt, ...(result.error ? { lastError: result.error } : {}) }; const finalLead = { ...sending, status: result.accepted ? "sent" as const : "delivery_failed" as const, updatedAt: completedAt, deliveries: [...sending.deliveries.filter((item) => item.id !== attempt.id), delivery], events: [...sending.events, statusEvent(result.accepted ? "sent" : "delivery_failed", session.userId, result.providerId || result.error || "Delivery completed")] }; await store.save(finalLead); return NextResponse.json({ lead: finalLead, provider: provider.name, verifiedExternalDelivery: process.env.OUTBOUND_EMAIL_PROVIDER === "webhook" });
  } catch (error) { if (error instanceof Error && error.name === "ZodError") return NextResponse.json({ error: "Invalid update" }, { status: 400 }); if (error instanceof Error && (error.message.startsWith("Invalid workflow") || error.message.includes("not configured"))) return NextResponse.json({ error: error.message }, { status: 409 }); return errorResponse(error); }
}
